### PR TITLE
Fix for issue #245 by checking the effective execution policy before …

### PR DESCRIPTION
**Pull request by kfuglsang**
…attempting to change to a possibly more restrictive policy

### CODE REVIEW

**Comment by adamdriscoll** [comment]
Looks good to me. /cc: @AndreSayreMSFT  @HuanhuanSunMSFT

**Comment by kfuglsang** [comment]
I've just installed it in VS 2015 RC and I can confirm that this has resolved the issue.

**Comment by AndreSayreMSFT** [comment]
Awesome!  Thanks for submitting this Pull Request to fix up the issue!   I did notice one potential edge case in the above fix:

If the Method is called to set it to something still more restrictive than current, but the current policy is not Unrestricted, we'll have the same issue.

Psuedo code:

if( policy <= currentPolicy || currentPolicy == Bypass) //Bypass is the absolute least restrictive, but as added in PS 2.0, and thus has a value of '4' instead of a value that corresponds to it's relative restrictiveness
{
return;
}

@kfuglsang @adamdriscoll  : Thoughts?

**Comment by kfuglsang** [comment]
Looks good to me. I just updated the PR with it.

**Comment by adamdriscoll** [comment]
Thanks! Merged.

**Pull request merged**
