### PR TITLE
Shared Project Update

### PR DESCRIPTION
**Pull request by adamdriscoll**
Fixes https://github.com/Microsoft/poshtools/issues/59

### CODE REVIEW

**Comment by adamdriscoll** [comment]
@AndreSayreMSFT I know there might not be a blessed build of the shared project but this is way more inline with what is currently being used by PTVS and NTVS. It seems to be working just fine at the moment.

**Comment by AndreSayreMSFT** [comment]
Which unblessed build was it?  [Is there a major difference from one of the RTM builds of [P/N]TVS?]

There are a bunch of files which aren't applicable [for example, a bunch of stuff in build] and aren't necessarily applicable to PoshTools :)

image
(History of /SharedProject)  Do these items need to be ported over and updated in the new shared proj stuff?

**Comment by adamdriscoll** [comment]
@AndreSayreMSFT I grabbed the latest from the PyTools GH repo. There were a lot of changes and I have already noticed a few things that work better but aren't yet implemented in PoshTools such as references and WPF designer support. I need to do an audit of the commits you mention to see where we lie. I figured I'd create this PR. It'd be really nice if there was just a NuGet package for the shared project stuff....

**Comment by adamdriscoll** [comment]
Just found out about this: https://visualstudiogallery.msdn.microsoft.com/31e107b7-b0ce-4236-8ffa-ed35f03397b8 

https://github.com/Microsoft/VSProjectSystem

Seems like a better option.

**Comment by AndreSayreMSFT** [comment]
@adamdriscoll Agreed, using CPS Would be all kinds of awesome, as from VS's side, it wasn't realistic to have to have every project manage its own projecting system in the way [N|P]TVS/PoshTools do.

There is one consideration: CPS hasn't been fully brought to Dev12(VS2013) -- Though a migration where we're just conditional-ing out Dev12/Dev14+ stuff would be awesome!

**Pull request closed without merging**
